version: '3.7'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - ~/.gitconfig:/root/.gitconfig
    ports:
      - 2121:2121
    command: sleep infinity